image: maven:3.3-jdk-8

pipelines:
  default:
    - step:
        script:
          - git remote rename origin upstream
          - mvn -V -B -s .ci/settings.xml clean install -DskipITs
          - git remote rename upstream origin
  branches:
    master:
      - step:
          script:
            - git remote rename origin upstream
            - mvn -V -B -s .ci/settings.xml clean install
            - mvn -B -s .ci/settings.xml deploy -DskipTests -DskipITs
            - git remote rename upstream origin
  tags:
    solrlib-*:
      - step:
          script:
            - git remote rename origin upstream
            - mvn -V -B -s .ci/settings.xml clean install
            - mvn -B -s .ci/settings.xml deploy -DskipTests -DskipITs
            - git remote rename upstream origin